version: '3.8'

services:
 server-node:
  build:
   context: ./backend-node
  ports:
   - 8080:8080
  environment:
   - SERVER_PORT=8080
  volumes:
   - ./backend-node/src:/app/src
  command: npm run dev