version: '3.8'

services:
 rover:
  build:
   context: ./rover
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000

 rover-ui:
  build:
   context: ./rover-ui
  ports:
   - 8000:8000
  volumes:
   - ./rover-ui/src:/app/src

 server-node:
  build:
   context: ./backend-node
  ports:
   - 4000:4000
  environment:
   - SERVER_PORT=4000
  volumes:
   - ./backend-node/src:/app/src
  command: npm run dev